### ISSUE TITLE
TicTacToe V1.0 - Game texts doesn't fit device screen if no player name was entered

### ISSUE THREAD

**Issue by realrufans** [mRahulJain/TicTacToe#1]
**Describe the bug**
When a user doesn't enter a player name, the game texts, and buttons won't fit the screen.

**To Reproduce**

- launch the game

- click on play game ( without entering a player name)

- watch it not fit the screen.

## Expected behavior
 
Expected the game to prevent the user from playing if the users doesn't enter a name.

## Screenshots

![Screenshot_20190625-135933.png](https://cdn.steemitimages.com/DQmSg1TiP9gLPWAvHop4Q7S3GrWTWm88vLA5roz37PePZJx/Screenshot_20190625-135933.png)

## Test environment 

 - Device: Tecno xpro
 - OS: Android 8.1

**Comment by mRahulJain** [comment]
Hey, I have properly used a linear layout (vertical orientation) of width and height match_parent, inside which my other layouts have been placed. I have not encountered any such issue still.
However, I will work on this. 
Try the updated version of this game.
Thanks!

**Comment by realrufans** [comment]
[The latest version](https://github.com/mRahulJain/TicTacToe/blob/master/app/release/app-release.apk) didn't install.

**Comment by mRahulJain** [comment]
First uninstall the earlier version of this game, and then download the '.apk' file. Since this installation will be an unknown source, so try clicking "install anyways". I have done this in 2-3 cell phones and it works.
Hope it helps.
Thanks!

**Comment by realrufans** [comment]
Worked

**Comment by realrufans** [comment]
However, the restart button is still very large.
![Screenshot_20190626-151307.png](https://cdn.steemitimages.com/DQmcYa8sfHd3R7EZjyccgKoEDgFAXUKGMtq81yaDoonXpYE/Screenshot_20190626-151307.png)

**Comment by mRahulJain** [comment]
See, I have considered the issue you have shown. Try it again, I have again pushed the latest '.apk' file (condition: UNINSTALL the previous app)
But I guess the screen resolution matters here! Because the time your message popped up with an error, the game in my phone was functioning well.
![Screenshot_20190626-203333](https://user-images.githubusercontent.com/43337248/60191775-82c1f400-9852-11e9-8309-7ba49c44f453.jpg)
